// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "PlayDelta",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "PlayDelta",
            targets: ["AppModule"],
            bundleIdentifier: "com.rileytestut.PlayDelta",
            teamIdentifier: "6XVY5G3U44",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/rileytestut/DeltaCore.git", .branch("main")),
        .package(url: "https://github.com/rileytestut/Roxas.git", .branch("swiftpm")),
        .package(url: "https://github.com/rileytestut/Harmony.git", .branch("swiftpm")),
        .package(url: "https://github.com/rileytestut/GPGXDeltaCore.git", .branch("main")),
        .package(url: "https://github.com/stephencelis/SQLite.swift.git", "0.9.2"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "DeltaCore", package: "deltacore"),
                .product(name: "Roxas", package: "roxas"),
                .product(name: "Harmony", package: "harmony"),
                .product(name: "GPGXDeltaCore", package: "gpgxdeltacore"),
                .product(name: "SQLite", package: "sqlite.swift")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)